//
// RiskAnalyzerApp.swift
// RiskAnalyzer
//
// Generated by Universal Mobile App Generator
//

import SwiftUI

@main
struct RiskAnalyzerApp: App {
    @StateObject private var sparqlService = SPARQLService()

    var body: some Scene {
        WindowGroup {
            ContentView()
                .environmentObject(sparqlService)
                .onAppear {
                    Task {
                        await sparqlService.initialize()
                    }
                }
        }
    }
}
