//
// ComplianceCheckerApp.swift
// ComplianceChecker
//
// Generated by Universal Mobile App Generator
//

import SwiftUI

@main
struct ComplianceCheckerApp: App {
    @StateObject private var sparqlService = SPARQLService()

    var body: some Scene {
        WindowGroup {
            ContentView()
                .environmentObject(sparqlService)
                .onAppear {
                    Task {
                        await sparqlService.initialize()
                    }
                }
        }
    }
}
