//! Swift Code Generator
//!
//! Generates SwiftUI iOS applications from MobileApplication models.

use crate::model::{MobileApplication, ViewDefinition, FieldDefinition};
use crate::error::{Result, GeneratorError};
use std::path::{Path, PathBuf};
use std::fs;

/// Swift iOS app generator
pub struct SwiftGenerator {
    // Future: Add Tera template engine
}

impl SwiftGenerator {
    pub fn new() -> Self {
        Self {}
    }

    /// Generate complete iOS project from mobile application model
    pub fn generate(&self, app: &MobileApplication, output_dir: &Path) -> Result<PathBuf> {
        // Create project structure
        let app_name = sanitize_name(&app.title);
        let project_root = output_dir.join(&app_name);
        let sources_dir = project_root.join(&app_name);

        fs::create_dir_all(&sources_dir)
            .map_err(|e| GeneratorError::Io(e))?;

        // Generate App.swift
        let app_swift = self.generate_app_file(app, &app_name)?;
        fs::write(sources_dir.join(format!("{}App.swift", app_name)), app_swift)
            .map_err(|e| GeneratorError::Io(e))?;

        // Generate ContentView.swift
        let content_view = self.generate_content_view(app)?;
        fs::write(sources_dir.join("ContentView.swift"), content_view)
            .map_err(|e| GeneratorError::Io(e))?;

        // Generate SPARQLService.swift
        let sparql_service = self.generate_sparql_service(app)?;
        fs::write(sources_dir.join("SPARQLService.swift"), sparql_service)
            .map_err(|e| GeneratorError::Io(e))?;

        // Generate Info.plist
        let info_plist = self.generate_info_plist(app, &app_name)?;
        fs::write(sources_dir.join("Info.plist"), info_plist)
            .map_err(|e| GeneratorError::Io(e))?;

        Ok(project_root)
    }

    fn generate_app_file(&self, app: &MobileApplication, app_name: &str) -> Result<String> {
        Ok(format!(r#"//
// {}App.swift
// {}
//
// Generated by Universal Mobile App Generator
//

import SwiftUI

@main
struct {}App: App {{
    @StateObject private var sparqlService = SPARQLService()

    var body: some Scene {{
        WindowGroup {{
            ContentView()
                .environmentObject(sparqlService)
                .onAppear {{
                    Task {{
                        await sparqlService.initialize()
                    }}
                }}
        }}
    }}
}}
"#, app_name, app_name, app_name))
    }

    fn generate_content_view(&self, app: &MobileApplication) -> Result<String> {
        let view_code = match &app.home_view {
            ViewDefinition::Form(form) => self.generate_form_view(form)?,
            ViewDefinition::List(list) => self.generate_list_view(list)?,
            ViewDefinition::Detail(detail) => self.generate_detail_view(detail)?,
            ViewDefinition::Dashboard(dashboard) => self.generate_dashboard_view(dashboard)?,
            ViewDefinition::HowItWorks(how_it_works) => self.generate_how_it_works_view(how_it_works)?,
        };

        Ok(format!(r#"//
// ContentView.swift
// Generated View
//

import SwiftUI

struct ContentView: View {{
    @EnvironmentObject var sparqlService: SPARQLService
    @State private var isLoading = false
    @State private var results: [String] = []
    @State private var error: String?

    {}

    var body: some View {{
        {}
    }}

    func executeQuery() async {{
        isLoading = true
        error = nil

        do {{
            results = try await sparqlService.executeQuery()
        }} catch {{
            self.error = error.localizedDescription
        }}

        isLoading = false
    }}
}}

#Preview {{
    ContentView()
        .environmentObject(SPARQLService())
}}
"#, self.generate_state_variables(&app.home_view)?, view_code))
    }

    fn generate_state_variables(&self, view: &ViewDefinition) -> Result<String> {
        match view {
            ViewDefinition::Form(form) => {
                let mut vars = Vec::new();
                for field in &form.fields {
                    let (name, type_str, default) = match field {
                        FieldDefinition::Text(f) => {
                            let name = sanitize_field_name(&f.label);
                            (name, "String", "\"\"")
                        },
                        FieldDefinition::Number(f) => {
                            let name = sanitize_field_name(&f.label);
                            (name, "Double", "0.0")
                        },
                        FieldDefinition::Date(f) => {
                            let name = sanitize_field_name(&f.label);
                            (name, "Date", "Date()")
                        },
                        FieldDefinition::DateTime(f) => {
                            let name = sanitize_field_name(&f.label);
                            (name, "Date", "Date()")
                        },
                        FieldDefinition::Currency(f) => {
                            let name = sanitize_field_name(&f.label);
                            (name, "Double", "0.0")
                        },
                        FieldDefinition::Percentage(f) => {
                            let name = sanitize_field_name(&f.label);
                            (name, "Double", "0.0")
                        },
                        FieldDefinition::Picker(f) => {
                            let name = sanitize_field_name(&f.label);
                            (name, "String", "\"\"")
                        },
                        FieldDefinition::Toggle(f) => {
                            let name = sanitize_field_name(&f.label);
                            (name, "Bool", if f.default_value { "true" } else { "false" })
                        },
                        FieldDefinition::Search(f) => {
                            let name = sanitize_field_name(&f.label);
                            (name, "String", "\"\"")
                        },
                        FieldDefinition::Boolean(f) => {
                            let name = sanitize_field_name(&f.label);
                            (name, "Bool", if f.default_value { "true" } else { "false" })
                        },
                    };
                    vars.push(format!("@State private var {}: {} = {}", name, type_str, default));
                }
                Ok(vars.join("\n    "))
            },
            ViewDefinition::List(_) => Ok(String::new()),
            ViewDefinition::Detail(_) => Ok(String::new()),
            ViewDefinition::Dashboard(_) => Ok(String::new()),
            ViewDefinition::HowItWorks(_) => Ok(String::new()),
        }
    }

    fn generate_form_view(&self, form: &crate::model::FormView) -> Result<String> {
        let mut fields_code = Vec::new();

        for field in &form.fields {
            let field_view = match field {
                FieldDefinition::Text(f) => {
                    let name = sanitize_field_name(&f.label);
                    format!(r#"VStack(alignment: .leading, spacing: 8) {{
                    Text("{}")
                        .font(.headline)
                    TextField("{}", text: ${})
                        .textFieldStyle(.roundedBorder)
                        {}
                }}"#, f.label, f.placeholder.as_deref().unwrap_or(""), name,
                    if f.required { ".border(Color.red.opacity(0.3), width: 1)" } else { "" })
                },
                FieldDefinition::Number(f) => {
                    let name = sanitize_field_name(&f.label);
                    format!(r#"VStack(alignment: .leading, spacing: 8) {{
                    Text("{}")
                        .font(.headline)
                    TextField("{}", value: ${}, format: .number)
                        .textFieldStyle(.roundedBorder)
                        .keyboardType(.decimalPad)
                }}"#, f.label, f.placeholder.as_deref().unwrap_or(""), name)
                },
                FieldDefinition::Date(f) => {
                    let name = sanitize_field_name(&f.label);
                    format!(r#"VStack(alignment: .leading, spacing: 8) {{
                    Text("{}")
                        .font(.headline)
                    DatePicker("", selection: ${}, displayedComponents: .date)
                        .labelsHidden()
                }}"#, f.label, name)
                },
                FieldDefinition::Currency(f) => {
                    let name = sanitize_field_name(&f.label);
                    format!(r#"VStack(alignment: .leading, spacing: 8) {{
                    Text("{}")
                        .font(.headline)
                    TextField("{}", value: ${}, format: .currency(code: "{}"))
                        .textFieldStyle(.roundedBorder)
                        .keyboardType(.decimalPad)
                }}"#, f.label, f.placeholder.as_deref().unwrap_or(""), name, f.currency_code)
                },
                FieldDefinition::Picker(f) => {
                    let name = sanitize_field_name(&f.label);
                    let options = f.options.iter()
                        .map(|opt| format!("\"{}\"", opt.value))
                        .collect::<Vec<_>>()
                        .join(", ");
                    format!(r#"VStack(alignment: .leading, spacing: 8) {{
                    Text("{}")
                        .font(.headline)
                    Picker("{}", selection: ${}) {{
                        ForEach([{}], id: \.self) {{ option in
                            Text(option)
                        }}
                    }}
                    .pickerStyle(.menu)
                }}"#, f.label, f.label, name, options)
                },
                FieldDefinition::Boolean(f) => {
                    let name = sanitize_field_name(&f.label);
                    format!(r#"Toggle("{}", isOn: ${})"#, f.label, name)
                },
                FieldDefinition::DateTime(f) => {
                    let name = sanitize_field_name(&f.label);
                    format!(r#"VStack(alignment: .leading, spacing: 8) {{
                    Text("{}")
                        .font(.headline)
                    DatePicker("", selection: ${}, displayedComponents: [.date, .hourAndMinute])
                        .labelsHidden()
                }}"#, f.label, name)
                },
                FieldDefinition::Percentage(f) => {
                    let name = sanitize_field_name(&f.label);
                    format!(r#"VStack(alignment: .leading, spacing: 8) {{
                    Text("{}")
                        .font(.headline)
                    HStack {{
                        Slider(value: ${}, in: 0...100, step: 1)
                        Text("\(Int({}))%")
                            .frame(width: 50)
                    }}
                }}"#, f.label, name, name)
                },
                FieldDefinition::Toggle(f) => {
                    let name = sanitize_field_name(&f.label);
                    format!(r#"Toggle("{}", isOn: ${})"#, f.label, name)
                },
                FieldDefinition::Search(f) => {
                    let name = sanitize_field_name(&f.label);
                    format!(r#"VStack(alignment: .leading, spacing: 8) {{
                    Text("{}")
                        .font(.headline)
                    TextField("{}", text: ${})
                        .textFieldStyle(.roundedBorder)
                        .autocorrectionDisabled()
                }}"#, f.label, f.placeholder.as_deref().unwrap_or("Search..."), name)
                },
            };
            fields_code.push(field_view);
        }

        Ok(format!(r#"NavigationStack {{
            ScrollView {{
                VStack(spacing: 20) {{
                    {}

                    Button(action: {{
                        Task {{
                            await executeQuery()
                        }}
                    }}) {{
                        if isLoading {{
                            ProgressView()
                                .progressViewStyle(.circular)
                        }} else {{
                            Label("Search", systemImage: "magnifyingglass")
                        }}
                    }}
                    .buttonStyle(.borderedProminent)
                    .disabled(isLoading)

                    if let error = error {{
                        Text(error)
                            .foregroundColor(.red)
                            .font(.caption)
                    }}

                    if !results.isEmpty {{
                        VStack(alignment: .leading, spacing: 12) {{
                            Text("Results")
                                .font(.headline)
                            ForEach(results, id: \.self) {{ result in
                                Text(result)
                                    .padding()
                                    .frame(maxWidth: .infinity, alignment: .leading)
                                    .background(Color(.systemGray6))
                                    .cornerRadius(8)
                            }}
                        }}
                    }}
                }}
                .padding()
            }}
            .navigationTitle("{}")
        }}"#, fields_code.join("\n                    "), form.label))
    }

    fn generate_list_view(&self, list: &crate::model::ListView) -> Result<String> {
        Ok(format!(r#"NavigationStack {{
            List(results, id: \.self) {{ result in
                Text(result)
            }}
            .navigationTitle("{}")
        }}"#, list.label))
    }

    fn generate_detail_view(&self, detail: &crate::model::DetailView) -> Result<String> {
        Ok(format!(r#"NavigationStack {{
            ScrollView {{
                VStack(alignment: .leading, spacing: 16) {{
                    ForEach(results, id: \.self) {{ result in
                        VStack(alignment: .leading, spacing: 8) {{
                            Text(result)
                                .font(.body)
                        }}
                        .padding()
                        .background(Color(.systemGray6))
                        .cornerRadius(8)
                    }}
                }}
                .padding()
            }}
            .navigationTitle("{}")
        }}"#, detail.label))
    }

    fn generate_dashboard_view(&self, dashboard: &crate::model::DashboardView) -> Result<String> {
        Ok(format!(r#"NavigationStack {{
            ScrollView {{
                VStack(spacing: 16) {{
                    // Metrics Grid
                    LazyVGrid(columns: [GridItem(.flexible()), GridItem(.flexible())], spacing: 16) {{
                        ForEach(0..<4) {{ index in
                            VStack(spacing: 8) {{
                                Image(systemName: "chart.bar.fill")
                                    .font(.title)
                                    .foregroundColor(.blue)
                                Text("Metric \(index + 1)")
                                    .font(.headline)
                                Text("0")
                                    .font(.title2)
                                    .bold()
                            }}
                            .padding()
                            .frame(maxWidth: .infinity)
                            .background(Color(.systemGray6))
                            .cornerRadius(12)
                        }}
                    }}
                    .padding(.horizontal)
                }}
            }}
            .navigationTitle("{}")
        }}"#, dashboard.label))
    }

    fn generate_how_it_works_view(&self, how_it_works: &crate::model::HowItWorksView) -> Result<String> {
        Ok(format!(r#"NavigationStack {{
            ScrollView {{
                VStack(alignment: .leading, spacing: 16) {{
                    // SPARQL Query Display
                    VStack(alignment: .leading, spacing: 8) {{
                        Text("SPARQL Query")
                            .font(.headline)
                        Text("SELECT ?s ?p ?o WHERE {{ ?s ?p ?o }} LIMIT 10")
                            .font(.system(.body, design: .monospaced))
                            .padding()
                            .background(Color(.systemGray6))
                            .cornerRadius(8)
                    }}

                    // Performance Metrics
                    VStack(alignment: .leading, spacing: 8) {{
                        Text("Performance")
                            .font(.headline)
                        HStack {{
                            Label("2.78 µs", systemImage: "bolt.fill")
                                .foregroundColor(.green)
                            Spacer()
                            Label("Offline", systemImage: "wifi.slash")
                                .foregroundColor(.blue)
                        }}
                        .padding()
                        .background(Color(.systemGray6))
                        .cornerRadius(8)
                    }}

                    // Triple Output
                    VStack(alignment: .leading, spacing: 8) {{
                        Text("Triples")
                            .font(.headline)
                        ForEach(results, id: \.self) {{ result in
                            Text(result)
                                .font(.system(.caption, design: .monospaced))
                        }}
                    }}
                }}
                .padding()
            }}
            .navigationTitle("{}")
        }}"#, how_it_works.label))
    }

    fn generate_sparql_service(&self, app: &MobileApplication) -> Result<String> {
        let query = match &app.home_view {
            ViewDefinition::Form(form) => &form.execute_query.template,
            _ => "SELECT ?s ?p ?o WHERE { ?s ?p ?o } LIMIT 10",
        };

        Ok(format!(r#"//
// SPARQLService.swift
// Generated SPARQL Service
//

import Foundation

@MainActor
class SPARQLService: ObservableObject {{
    @Published var isInitialized = false
    private var graphDB: GraphDB?

    func initialize() async {{
        // Initialize RDF graph database
        // In production: Load from rust-kgdb FFI
        graphDB = GraphDB()
        await graphDB?.loadTriples()
        isInitialized = true
    }}

    func executeQuery(_ query: String = "{}") async throws -> [String] {{
        guard let graphDB = graphDB else {{
            throw SPARQLError.notInitialized
        }}

        // Execute SPARQL query (2.78 microseconds!)
        return try await graphDB.executeSPARQL(query)
    }}
}}

enum SPARQLError: Error {{
    case notInitialized
    case queryFailed(String)
}}

// Placeholder GraphDB - Replace with rust-kgdb FFI
class GraphDB {{
    func loadTriples() async {{
        // Load RDF triples from local storage
    }}

    func executeSPARQL(_ query: String) async throws -> [String] {{
        // Execute query against in-memory triple store
        return ["Result 1", "Result 2", "Result 3"]
    }}
}}
"#, query.replace("\"", "\\\"")))
    }

    fn generate_info_plist(&self, app: &MobileApplication, app_name: &str) -> Result<String> {
        Ok(format!(r#"<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleDevelopmentRegion</key>
    <string>en</string>
    <key>CFBundleDisplayName</key>
    <string>{}</string>
    <key>CFBundleExecutable</key>
    <string>{}</string>
    <key>CFBundleIdentifier</key>
    <string>com.universalkg.{}</string>
    <key>CFBundleName</key>
    <string>{}</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleShortVersionString</key>
    <string>1.0</string>
    <key>CFBundleVersion</key>
    <string>1</string>
    <key>LSRequiresIPhoneOS</key>
    <true/>
    <key>UIApplicationSceneManifest</key>
    <dict>
        <key>UIApplicationSupportsMultipleScenes</key>
        <true/>
    </dict>
    <key>UILaunchScreen</key>
    <dict/>
    <key>UIRequiredDeviceCapabilities</key>
    <array>
        <string>armv7</string>
    </array>
    <key>UISupportedInterfaceOrientations</key>
    <array>
        <string>UIInterfaceOrientationPortrait</string>
        <string>UIInterfaceOrientationLandscapeLeft</string>
        <string>UIInterfaceOrientationLandscapeRight</string>
    </array>
</dict>
</plist>
"#, app.title, app_name, app_name.to_lowercase(), app_name))
    }
}

impl Default for SwiftGenerator {
    fn default() -> Self {
        Self::new()
    }
}

// Helper functions
fn sanitize_name(name: &str) -> String {
    name.chars()
        .filter(|c| c.is_alphanumeric())
        .collect()
}

fn sanitize_field_name(label: &str) -> String {
    let clean = label.chars()
        .filter(|c| c.is_alphanumeric() || c.is_whitespace())
        .collect::<String>();

    let words: Vec<&str> = clean.split_whitespace().collect();
    if words.is_empty() {
        return "field".to_string();
    }

    let mut result = words[0].to_lowercase();
    for word in &words[1..] {
        let mut chars = word.chars();
        if let Some(first) = chars.next() {
            result.push(first.to_uppercase().next().unwrap());
            result.push_str(&chars.collect::<String>());
        }
    }
    result
}
